spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG

server:
  port: 8080
